# Practise Questions of Pandas

Question 1 : create a series using a list of 5 fruit names. Assign custom index to each element.

In [1]:
import pandas as pd

s = pd.Series(['apple','banana','cherry','watermelon','orange'], index=['one','two','three','four','five'])
s

one           apple
two          banana
three        cherry
four     watermelon
five         orange
dtype: object

Question 2: create a dataframe from the following dictionary:

{
    'name' : ['alice','bob','charlie'],
    'age' : [25,30,40],
    'city' : ['pune','mummbai','nasikh']
}

In [2]:
df = pd.DataFrame({'name':['alice','bob','charlie'],'age':[25,30,35],'city':['new york','los angeles','chicago']})
df

      name  age         city
0    alice   25     new york
1      bob   30  los angeles
2  charlie   35      chicago

Question 3: using the DataFrame form question2, display - first 2 row, lasst row, shape of the DataFrame

In [4]:
print(df.head(2))
print(df.tail(1))
print(df.shape)

    name  age         city
0  alice   25     new york
1    bob   30  los angeles
      name  age     city
2  charlie   35  chicago
(3, 3)

question 4: use .info() and .describe() on the dataframe created in question2.

In [ ]:
print(df.info()) # Get summary information about the DataFrame
print(df.describe()) # Get statistical summary of numerical columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
        age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

question 5: from the dataframe in ques2, select only the 'name' and 'city' colums using loc.

In [7]:
df.loc[:,['name','city']]

      name         city
0    alice     new york
1      bob  los angeles
2  charlie      chicago

Question 6: from the DataFrame, use iloc to display the second row

In [8]:
df.iloc[2:3,:]

      name  age     city
2  charlie   35  chicago

Question 7: rename the 'age' column to 'years' in the DataFrame

In [17]:
ag= {'age':'Years'}
df.rename(columns=ag, inplace=True) #inplace=True to modify the original DataFrame
df

      name  Years         city
0    alice     30     new york
1      bob     35  los angeles
2  charlie     40      chicago

question 8: drop the 'city' column from the dataframe

In [ ]:
df.drop('city' , axis=1) # axis is used to specify whether to drop rows (0) or columns (1)

      name  age
0    alice   25
1      bob   30
2  charlie   35

question 9: modify the 'years' column by addding 5 to each value

In [18]:
df['Years'] = df['Years'] + 5
df

      name  Years         city
0    alice     35     new york
1      bob     40  los angeles
2  charlie     45      chicago