# Pandas in python

Pandas is an open source library for data manipulation, analysis and cleaning. It provides tools to work with tabular data, similar to spreadsheets and SQL tables.

Pandas is used in data science, machine learning, finance, analytics and automation because it integrates smoothly with other libraries.

Pandas_Basic_Operation:
Data processing
Data cleaning
Data transformation
Data visualization 

Creating_Data:
There are two core objects in pandas: the DataFrames and the Series.

DataFrame:
A dataframe is a table, it contains an array of individual entries(column), each of which has a certain value(row), and these are indexed.

In [93]:
import pandas as pd

df = pd.DataFrame({'mahek':[12,43,65,54], 'Sayma' :[23,45,67,89]})

print("DataFrame created successfully.")

print(df)

DataFrame created successfully.
   mahek  Sayma
0     12     23
1     43     45
2     65     67
3     54     89

so in this example, mahek at '0' has value 12. and sayma at '0' has value 23.

we can also save strings in dataframes.

we are basically creating a dictionary whose keys are the column names and whose values are the list of entries.

we are using the pd.DataFrame() contructor to generate these DataFrame objects.

The list of row labels used in DataFrame is known as an Index.[0,1,2,3] we can assign values to it by using an index parametere in our contructor

In [94]:
import pandas as pd
df= pd.DataFrame({'mahek':['wow!thats great!', 'umm, its ok ok'], 'sayma':['meh! i dont rly like it.', 'yayyy!! i love it!']},
                 index=['The park','The mall'])
print('Second DataFrame using strings and custom index:')
print(df)
print(df['mahek']['The park'])

Second DataFrame using strings and custom index:
                     mahek                     sayma
The park  wow!thats great!  meh! i dont rly like it.
The mall    umm, its ok ok        yayyy!! i love it!
wow!thats great!

so when we rename the index, its original name is changed, so basically now if u want to print 'the park' value of 'mahek'

print(df['mahek']['The park'])- this will print the entry of that particular cell. yaha pe aapn 'ab' dictonary ke andar, 'mahek' column ke 'the park' row is entry nikalre. tho itna specify karna padhta.

In [95]:
roll = [101, 102, 103, 104]
name = ['mahek', 'sayma', 'nishi', 'ritu']
marks = [95, 85, 75, 65]

df = pd.DataFrame({'ID':roll, 'Name':name, 'Marks':marks})
df

    ID   Name  Marks
0  101  mahek     95
1  102  sayma     85
2  103  nishi     75
3  104   ritu     65

In [96]:
df.shape #gives number of rows and columns

(4, 3)

In [97]:
df.size #gives size of series

12

In [98]:
df.columns #gives column labels

Index(['ID', 'Name', 'Marks'], dtype='object')

In [99]:
df.index = range(1, 5) #gives row labels, basically changes the index of the dataframe.
df

    ID   Name  Marks
1  101  mahek     95
2  102  sayma     85
3  103  nishi     75
4  104   ritu     65

In [100]:
import os
os.getcwd()  #gives current working directory

'c:\\Users\\mahek\\GitHub\\mituinternship\\Python\\Practical'

In [101]:
df = pd.read_csv('month.csv')  #reads a csv file and creates a dataframe
df

         Name Abbreviation  Numeric  Numeric-2
0     January         Jan.        1          1
1    Feburary         Feb.        2          2
2       March         Mar.        3          3
3       April         Apr.        4          4
4         May          May        5          5
5        June         June        6          6
6        July         July        7          7
7      August         Aug.        8          8
8   September        Sept.        9          9
9     October         Oct.       10         10
10   November         Nov.       11         11
11   December         Dec.       12         12

In [102]:
headers = ['a' , 'b', 'c', 'd']
df = pd.read_csv('month.csv', names = headers) #reads a csv file and creates a dataframe with custom headers
df

            a             b        c          d
0        Name  Abbreviation  Numeric  Numeric-2
1     January          Jan.        1         01
2    Feburary          Feb.        2         02
3       March          Mar.        3         03
4       April          Apr.        4         04
5         May           May        5         05
6        June          June        6         06
7        July          July        7         07
8      August          Aug.        8         08
9   September         Sept.        9         09
10    October          Oct.       10         10
11   November          Nov.       11         11
12   December          Dec.       12         12

In [103]:
df = pd.read_csv('month.csv', nrows=3)  #reads only first 3 rows of the csv file
df

       Name Abbreviation  Numeric  Numeric-2
0   January         Jan.        1          1
1  Feburary         Feb.        2          2
2     March         Mar.        3          3

In [104]:
df.shape  #gives number of rows and columns

(3, 4)

In [105]:
df.size  #gives size of series

12

In [106]:
df.info()  #gives concise summary of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          3 non-null      object
 1   Abbreviation  3 non-null      object
 2   Numeric       3 non-null      int64
 3   Numeric-2     3 non-null      int64
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes

In [107]:
df = pd.read_csv('month.csv', sep = '\t')  #here the file is seprated by commas but when we give a tab seprator the pandas does not find any \t in the file so it reads the whole row as a single column
df #whearas if the file was .tsv then it would have worked

   Name,Abbreviation,Numeric,Numeric-2
0                    January,Jan.,1,01
1                   Feburary,Feb.,2,02
2                      March,Mar.,3,03
3                      April,Apr.,4,04
4                         May,May,5,05
5                       June,June,6,06
6                       July,July,7,07
7                     August,Aug.,8,08
8                 September,Sept.,9,09
9                   October,Oct.,10,10
10                 November,Nov.,11,11
11                 December,Dec.,12,12

In [108]:
df = pd.read_csv('month.csv')
df.T #transpose of dataframe(rows become columns and columns become rows)

,0,1,2,3,4,5,6,7,8,9,10,11
Name,January,Feburary,March,April,May,June,July,August,September,October,November,December
Abbreviation,Jan.,Feb.,Mar.,Apr.,May,June,July,Aug.,Sept.,Oct.,Nov.,Dec.
Numeric,1,2,3,4,5,6,7,8,9,10,11,12
Numeric-2,1,2,3,4,5,6,7,8,9,10,11,12

In [109]:
df.dtypes  #gives data types of each column

Name            object
Abbreviation    object
Numeric          int64
Numeric-2        int64
dtype: object

In [110]:
df.head()  #gives first 5 rows of dataframe

       Name Abbreviation  Numeric  Numeric-2
0   January         Jan.        1          1
1  Feburary         Feb.        2          2
2     March         Mar.        3          3
3     April         Apr.        4          4
4       May          May        5          5

In [111]:
df.head(3)  #gives first 3 rows of dataframe

       Name Abbreviation  Numeric  Numeric-2
0   January         Jan.        1          1
1  Feburary         Feb.        2          2
2     March         Mar.        3          3

In [112]:
df.tail()  #gives last 5 rows of dataframe

         Name Abbreviation  Numeric  Numeric-2
7      August         Aug.        8          8
8   September        Sept.        9          9
9     October         Oct.       10         10
10   November         Nov.       11         11
11   December         Dec.       12         12

In [113]:
df.describe()  #gives statistical summary of dataframe

         Numeric  Numeric-2
count  12.000000  12.000000
mean    6.500000   6.500000
std     3.605551   3.605551
min     1.000000   1.000000
25%     3.750000   3.750000
50%     6.500000   6.500000
75%     9.250000   9.250000
max    12.000000  12.000000

loc and iloc are used for indexing and selecting specific rows and columns from pandas DataFrames and Series.

iloc - is used to do slicing using intergers [starting_row:ending_row, staring_column:ending_column]
Use when- 1. number of rows known 2. doing slicing of array or loops

loc - is used to do slicing using labels[staring_row_label:ending_row_labelstaring_col_label:ending_col_label]
Use when- 1.working with col names 2.flitering data 3.reable, production code

In [114]:
df.iloc[2:5, 0:3]  #slicing using iloc[row_start:row_end, col_start:col_end]

    Name Abbreviation  Numeric
2  March         Mar.        3
3  April         Apr.        4
4    May          May        5

In [115]:
df.iloc[[5,6,7], 0:2]  #slicing using iloc to get specific rows and columns

     Name Abbreviation
5    June         June
6    July         July
7  August         Aug.

In [117]:
df.loc[3:6,['Name','Numeric']]  #slicing using loc[row_labels, column_labels]

    Name  Numeric
3  April        4
4    May        5
5   June        6
6   July        7

In [118]:
df['Abbreviation']  #accessing a single column

0      Jan.
1      Feb.
2      Mar.
3      Apr.
4       May
5      June
6      July
7      Aug.
8     Sept.
9      Oct.
10     Nov.
11     Dec.
Name: Abbreviation, dtype: object

In [119]:
df.drop(7)  #drops the row with index label 7

         Name Abbreviation  Numeric  Numeric-2
0     January         Jan.        1          1
1    Feburary         Feb.        2          2
2       March         Mar.        3          3
3       April         Apr.        4          4
4         May          May        5          5
5        June         June        6          6
6        July         July        7          7
8   September        Sept.        9          9
9     October         Oct.       10         10
10   November         Nov.       11         11
11   December         Dec.       12         12

In [121]:
df.drop('Numeric', axis=1)  #drops the column with label 'Numeric', and axis=1 indicates that we are dropping a column because columns are along axis 1

         Name Abbreviation  Numeric-2
0     January         Jan.          1
1    Feburary         Feb.          2
2       March         Mar.          3
3       April         Apr.          4
4         May          May          5
5        June         June          6
6        July         July          7
7      August         Aug.          8
8   September        Sept.          9
9     October         Oct.         10
10   November         Nov.         11
11   December         Dec.         12

In [122]:
col = {'Name': 'Month'}
df.rename(columns=col)  #renames the column 'Name' to 'Month'

        Month Abbreviation  Numeric  Numeric-2
0     January         Jan.        1          1
1    Feburary         Feb.        2          2
2       March         Mar.        3          3
3       April         Apr.        4          4
4         May          May        5          5
5        June         June        6          6
6        July         July        7          7
7      August         Aug.        8          8
8   September        Sept.        9          9
9     October         Oct.       10         10
10   November         Nov.       11         11
11   December         Dec.       12         12

In [123]:
inx = {1:'one', 2:'two', 3:'three'}
df.rename(index=inx)  #renames the row labels 1,2,3 to one,two,three

            Name Abbreviation  Numeric  Numeric-2
0        January         Jan.        1          1
one     Feburary         Feb.        2          2
two        March         Mar.        3          3
three      April         Apr.        4          4
4            May          May        5          5
5           June         June        6          6
6           July         July        7          7
7         August         Aug.        8          8
8      September        Sept.        9          9
9        October         Oct.       10         10
10      November         Nov.       11         11
11      December         Dec.       12         12

In [ ]:
df['Numeric'] = df['Numeric'] * 2  #updates column 'Numeric' with double the values of column 'Numeric'
df

         Name Abbreviation  Numeric  Numeric-2
0     January         Jan.        4          1
1    Feburary         Feb.        8          2
2       March         Mar.       12          3
3       April         Apr.       16          4
4         May          May       20          5
5        June         June       24          6
6        July         July       28          7
7      August         Aug.       32          8
8   September        Sept.       36          9
9     October         Oct.       40         10
10   November         Nov.       44         11
11   December         Dec.       48         12

In [ ]:
df['Numeric-2']= df['Numeric-2'] +200  #updates 'Numeric-2' with values of column 'Numeric-2' plus 200
df

         Name Abbreviation  Numeric  Numeric-2
0     January         Jan.        4        201
1    Feburary         Feb.        8        202
2       March         Mar.       12        203
3       April         Apr.       16        204
4         May          May       20        205
5        June         June       24        206
6        July         July       28        207
7      August         Aug.       32        208
8   September        Sept.       36        209
9     October         Oct.       40        210
10   November         Nov.       44        211
11   December         Dec.       48        212

Series: a series is a sequence of data values, if a DataFrame is a teble, a series is a list. you can create a series with nothing more than a list.

In [40]:
import pandas as pd
s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

a series is a single column of dataframe, so we can assign row labels same as we did in dataframes, using the index parameter. however series does not have column name

In [41]:
import pandas as pd
s = pd.Series(['happy','calm','bummer','cold'], index=['mahek','sayma', 'zia','khadu'])
print(s)
print(s['zia'])

mahek     happy
sayma      calm
zia      bummer
khadu      cold
dtype: object
bummer

soo basically, here we can use directly the index name and not specify any other thing kyuki bas ek hi column hai :)

In [42]:
s1 = pd.Series([1,2,3,4,5])
s1.dtype # this shows the datatype of the series

dtype('int64')

In [43]:
s2 = pd.Series([1,2.0,3,4.6,7.3])
s2.dtype

dtype('float64')

In [44]:
s2[3] = 4.7 # changing element in the series
s2

0    1.0
1    2.0
2    3.0
3    4.7
4    7.3
dtype: float64

In [45]:
del s2[4] #deleting an element
s2

0    1.0
1    2.0
2    3.0
3    4.7
dtype: float64

In [46]:
s1.size #gives size of series

5

In [47]:
a = pd.Series([123,432,435,654,845,645], index = range(100,106)) # creating aeries with custom index, range keyword is used to give the limit of index
a

100    123
101    432
102    435
103    654
104    845
105    645
dtype: int64

In [48]:
print(a[103])

654